/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2025 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include "stm32f407xx.h"

void button_init(void);
void uart2_init(void);
void dma1_init(void);


#define BASE_ADDR_OF_GPIOA_PERI GPIOA

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

int main(void)
{
	button_init();
	uart2_init();
	dma1_init();
    /* Loop forever */
	for(;;);
}

void button_init(void){
	//Button is connected to PA0. GPIOA pin number 0
	GPIO_TypeDef *pGPIOA;
	pGPIOA = BASE_ADDR_OF_GPIOA_PERI;

	RCC_TypeDef *pRCC;
	pRCC= RCC;

	EXTI_TypeDef *pEXTI;
	pEXTI = EXTI;

	SYSCFG_TypeDef *pSYSCRG;
	pSYSCRG = SYSCFG;

	//1. Enable the peripheral clk for the GPIOA peripheral
	pRCC->AHB1ENR |= (1 << 0);

	//2. Keep the GPIO pin in I/P mode.
	pGPIOA->MODER &= ~(0x3 << 0);

	//3. Enable the interrupt over that GPIO pin.
	pEXTI->IMR = (1<<0);


	//4. Enable the clk for SYSCFG
	pRCC->APB2ENR |= (1 << 14);

	//5.  Configuring the SYSCFG CR1 register
	pSYSCRG->EXTICR[0] &= ~(0xF << 4);//Clearing
	pSYSCRG->EXTICR[0] |=  (0x0 << 4);//Setting

	//6. Configure the edge detection on the GPIO pin.
	pEXTI->FTSR = (1<<0);

	//7. Enable the IRQ related to that GPIO pin in NVIC-registere of the processor.
	NVIC_EnableIRQ(EXTI0_IRQn);
}
void uart2_init(void){

}
void dma1_init(void){

}

